### ISSUE TITLE
Any First Release?

### ISSUE THREAD

**Issue by kheos31** [mar10/wunderbaum#16]
Hi Martin!

A little question from our development already using fancytree historically.. Do you have any idea of when you will publish your first real release of this package ? We're actually trusting some solutions and this project sounds good for us, knowing the qualities and the defaults of actual fancytree.

Thanks in advance.
Regards

**Comment by vozvik** [comment]
It has been running quite stable I would say. I've been using regularly Wunderbaum and you have solved the issues I found and reported, Martin.
