### ISSUE TITLE
Incorrect source reference in MAP files of node_module

### ISSUE THREAD

**Issue by quijote** [mar10/wunderbaum#20]
I tried to use and debug wunderbaum in a React app. See https://github.com/mar10/wunderbaum/issues/19 for some background.

However running `npm start` resulted in the following warning:

```
WARNING in ./node_modules/wunderbaum/dist/wunderbaum.esm.min.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '...\wunderbaum_react_ts_demo\node_modules\wunderbaum\dist\build\wunderbaum.esm.js' file: Error: ENOENT: no such file or directory, open '...\\wunderbaum_react_ts_demo\node_modules\wunderbaum\dist\build\wunderbaum.esm.js'
```

Chrome then also did not allow to debug with the nonminified sources.

`wunderbaum.esm.min.js.map` contains:

```
"sources":["build/wunderbaum.esm.js"]
```

But there is no `build` directory in the `node_module`. 

The warning went away after I locally changed the MAP file to:

```
"sources":["wunderbaum.esm.js"]
```

`wunderbaum.esm.min.js.map` has a similar problem.

**Comment by mar10** [comment]
Seems fixed as per https://github.com/mar10/wunderbaum/issues/19#issuecomment-1575183741
