### ISSUE TITLE
Select / activated event order

### ISSUE THREAD

**Issue by RadekHavelka** [mar10/wunderbaum#27]
Hi,
  thank you for this tree component, been my favourite for years :) experimenting with new version of Wunderbaum (been using the original Fancytree, but wanna get rid of JQ) and I realised weird behavior of "activate" or "select" event. 
  
  I have tree with checkboxes, and I want to do something similar as existed in original Fancytree - get list of all selected nodes
`  tree.getSelectedNodes();`
  I understand no such function exists in the code of wunderbaum so far, so I wanted to replicate it using "select" event, by adding or removing the currently selected node to an array, or remove if unselected. But, If I call
  
```
  select: (e) => {
                    console.log(tree.getFocusNode().key);
                    console.log(tree.getFocusNode().selected);
                }
```

I am recieving FALSE for "selected", which is not correct - it should be TRUE. When I run the same code from the browser console afterwards

`                    console.log(tree.getFocusNode().selected);`

I get TRUE (which is the correct status of selection at that point). 

Looking into the code, I belive the event is fired BEFORE the status of the selection of the node is actually changed, is that correct? I mean this part of your code

```
 /** Modify the check/uncheck state. */
  setSelected(flag: boolean = true, options?: SetSelectedOptions) {
    const prev = this.selected;
    if (!!flag !== prev) {
      this._callEvent("select", { flag: flag });
    }
    this.selected = !!flag;
    this.update();
  }
```

Thank you

**Comment by mar10** [comment]
Thank you. I agree that this should be changed.
