### ISSUE TITLE
Access the Row from fixed HTML in Column definition

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#34]
column.html -> I have some fixed buttons in my designer, wich should be shown in each row, so I thought I can use this.
But how could I access the Row where the buttons are in?

Additional Feature:
Maybe the html property could also be a function wich returns a Node or a documentFragment?

**Comment by mar10** [comment]
Not sure if this helps, but you can get some information in the event handler:
```js
      const info = Wunderbaum.getEventInfo(e);
```

**Comment by jogibear9988** [comment]
I'll try :-)

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
i created the elements now in the render callback...
