### ISSUE TITLE
HTML in Title

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#38]
Hello,
in FancyTree I could completely replace the creation of the content, and so I allowed to use HTML in the title. 
I saw that I could change how you fill the columns via the render callback, but the main column '*' is not possible.

I think I could maybe fix this, by setting the with of the main column to 0px and create an additional one, but shouldn't this be possible?

**Comment by jogibear9988** [comment]
Okay, the 0px solution would not work, then also the tree navigation is not shown

**Comment by mar10** [comment]
Wunderbaum deliberately enforces HTML escaping for the title, mainly in order to prevent XSS.

You can inject HTML in the `render` callback however:
```js
  render: (e) => {
    e.nodeElem.querySelector("span.wb-title").innerHTML = `<u>${e.node.title}</u>`;
```

**Comment by jogibear9988** [comment]
works perfectly.
