### ISSUE TITLE
How to make Colum use MaxWidth and is scrollable

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#42]
SO, See in your example:

<img width="460" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/8efefacd-ffd2-405a-a22f-92d061d01480">

I've resized the Tree to 100px, and then all the texts are cut of and it's not scrollable.
In FancyTree I had it like that the column is always the needed size, and I could scroll to the right

**Comment by jogibear9988** [comment]
I could solve it via this extra styles:

      span.wb-node.wb-col {
        width: unset !important;
      }

      div.wunderbaum span.wb-node span.wb-title {
        text-overflow: unset;
        width: unset !important;
      }

don't know yet if that would be a good idea

**Comment by mar10** [comment]
We can change the (S)CSS, but need to be careful that it works in grid and fixed columns as well...

**Comment by jogibear9988** [comment]
yes, this now works for me (as a start), so atm I don't need a new feature or change.
If my designer changes are finished, I'll look to change FancyTree to Wunderbaum in my ioBroker UI, where I have a propertygrid using fancytree, wich also uses a table, so I will look then if and how it works
