### ISSUE TITLE
Expanded node jumps to Top - Make `scrollIntoView` flag default to false

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#46]
If you exand a node wich is bigger then the wunderbaum size, it jumps to the top. In fancytree the node stayed at the same place. The fancytree behavior was more expected

**Comment by jogibear9988** [comment]
There are many "setExpanded" calls without any Parameters, wich then use the defaults.

Should we enable to hand over the the defaults for expansion via the wunderbaum constructor?

**Comment by mar10** [comment]
> If you exand a node wich is bigger then the wunderbaum size, it jumps to the top. In fancytree the node stayed at the same place. The fancytree behavior was more expected

Try passing {scrollIntoView: false}

> There are many "setExpanded" calls without any Parameters, wich then use the defaults.

You're right. I rather consider this a bug, since the scrollIntoView flag is documented as 'default: false', but behaves otherwise.
Will rename this issue accordingly.

**Comment by jogibear9988** [comment]
Try passing {scrollIntoView: false}

I could not, as the setExpanded is called inside

**Comment by mar10** [comment]
Fixed with dbc931a0a8cce12bab96fa57786b78e003bfa30e
