### ISSUE TITLE
Drag Events not used....

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#48]
dragDrag, dragEnd, dragOver and dragLeave are not used

**Comment by mar10** [comment]
The D'n'd API was mainly copied over from Fancytree, but is not fully implemented yet

**Comment by jogibear9988** [comment]
Should I look after? Or will you do?

**Comment by mar10** [comment]
It's on my list somewhere, but no ETA.
If you need it, a PR would be great.

**Comment by jogibear9988** [comment]
Okay, will look for it
