### ISSUE TITLE
Types not used inside of wunderbaum code

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#49]
Is there any reason, why you don't use many of the types inside of the wunderbaum code, only in the types file?

**Comment by mar10** [comment]
Can you give some examples?

**Comment by jogibear9988** [comment]
I will

**Comment by jogibear9988** [comment]
Mostly in the DragAnDrop Code, but maybe it's because this was not yet finished.
I'll look, if find some places I'll look how it could be done better, and will create a pull req.
