### ISSUE TITLE
Persistence: Workaround inquiry

### ISSUE THREAD

**Issue by dpigera** [mar10/wunderbaum#5]
Hey @mar10, 
I'm very much looking forward to using your library. I've been using FancyTree for many years and your upgrades are fantastic. 

I do use the `persist` extension for FancyTree for remembering the expand/collapse state of my tree between webpage reloads. Do you have a recommendation on a workaround for this in the interim?

**Comment by mar10** [comment]
The persistence extensio will probably be ported to WB, but not highest priotity right now.
An implementation would probably track and persist  changes in the `expand` event amd restore it on `init`
Since you closed this: Did you implement a workaround? The we could add it as 'howto' for now
