### ISSUE TITLE
Wunderbaum object inside Bulma CSS ."columns .column" selector expands dropdown height infinitely

### ISSUE THREAD

**Issue by adkinsrs** [mar10/wunderbaum#57]
I noticed this behavior in a page I was building and ultimately traced it to the ".columns .column" selector that I use (from Bulma CSS).  Basically the ".wb-list-container" class keeps expanding height in a infinite loop (and the console show infinite Wunderbaum debug logs). If I hide the element (my main code has a collapsable component), the height stops expanding, but if the Wunderbaum dropdown is visible again, height starts to expand where it left off.  I wrapped the "#genecart_query" and "#genecart_tree" elements in an extra nested "div" and the behavior is the same.

I am currently using the 0.3.5 version of Wunderbaum.

Reproducible code
```html
<html>
    <head>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.5.95/css/materialdesignicons.min.css" />

        <!-- Tree view/grid -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/mar10/wunderbaum@v0.3.5/dist/wunderbaum.css">
    </head>
    <body>
        <div class="columns">
            <div class="column">
                <input class="input" id="genecart_query" type="text" placeholder="Enter a gene collection" autofocus="" />
                <div id="genecart_tree" class="wb-skeleton wb-initializing"></div>
            </div>
        </div>

        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/mar10/wunderbaum@v0.3.5/dist/wunderbaum.umd.min.js"></script>
        <script>
            const geneCartTree = new mar10.Wunderbaum({
                // https://mar10.github.io/wunderbaum/api/interfaces/wb_options.WunderbaumOptions.htm
                element: document.getElementById("genecart_tree"),
                filter: {
                    // https://github.com/mar10/wunderbaum/blob/c393a7a4e01a8c6bb9084002d3a70b9e18bcc974/src/wb_ext_filter.ts
                    connectInput: "input#genecart_query",
                    autoExpand: true,
                    mode: "hide",
                },
                types: {
                    folder: {icon: "mdi mdi-folder"},
                    show: {icon: "mdi mdi-card-account-details-outline"}
                },
                autoCollapse: true,
                //event handlers
                init: (e) => {
                    // After tree is created and data is loaded
                    e.tree.setFocus();
                },
            });

        </script>
    </body>

</html>


```

**Comment by adkinsrs** [comment]
Updated to the latest Wunderbaum version (0.5.1) and the issue still persists.  I also set `overflow-y: hidden` on the ".column" div as well as the ".columns" div and the same thing happens.  I did notice that if I set an explicit height then the auto-increment of the height does not occur. So I will try to implement some "max-height" solution to address this.

**Comment by jorvis** [comment]
> Hello,
> 
> this is not easy to reproduce for us, since the the incudes (js and css) are not available. Have you tried with the latest version? Another thing you could try is: set `overflow: hidden` to the outer container.

They are all full http URLs - how are they not available to you?

**Comment by mar10** [comment]
> They are all full http URLs - how are they not available to you?

The initial text contained `"css/gear-theme-purple.css" />`

I will look into it

**Comment by adkinsrs** [comment]
> > They are all full http URLs - how are they not available to you?
> 
> The initial text contained `"css/gear-theme-purple.css" />`
> 
> I will look into it

In hindsight, I should have included an explicit "edit" tag to indicate that I realized that mistake and corrected it.

**Comment by mar10** [comment]
The tree will automatically adjust its height to fit the parent container. 
This is useful when the tree is embedded in a container with a fixed or calculated sized. <br>

 If the parent container is unsized (e.g. grows with its content, `height: auto`),
 then we can define a `height: ...` or `max_height: ...` style on the parent:

```css
div.column {
  max-height: 100vh;
}
```

 To avoid a recursive resize-loop, it may be helpful to set `overflow: hidden` on the parent container.

I am planning to add an option to disable auto-resizing.

Interestingly the problem did not occur in Safari, but Chrome, Firefox, and Edge.
