### ISSUE TITLE
Problem with wunderbaum eventlisteners

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#61]
Hello,

I create my own controls in wunderbaum, using the "render" callback.

Now the Problem is, wunderbaum adds eventlisteners to the change event of all input fields. 
(It's done here: https://github.com/mar10/wunderbaum/blob/c1444b6862a71b5c8deafd10dfad2ec47434de0d/src/wb_ext_edit.ts#L47)

Is there a way to disable the edit extension?

**Comment by jogibear9988** [comment]
Cause I'm getting exceptions in wunderbaum cause of the "change" event raised by my own controls (I also could not prevent them, cause wunderbaum's eventlistener is called first)

**Comment by mar10** [comment]
Handling native 'change' events of embedded controls, and generating custom change events from this per node is the basic idea of editable grids.
This should however not raise exceptions. Can you give more details about use case and errors please?

**Comment by jogibear9988** [comment]
I get this error:

          getEventInfo @ wunderbaum.esm.min.js:85
          _onChange @ wunderbaum.esm.min.js:73
          f @ wunderbaum.esm.min.js:22
          b @ wunderbaum.esm.min.js:22
          v @ wunderbaum.esm.min.js:22
          setTimeout (async)
          g @ wunderbaum.esm.min.js:22
          (anonymous) @ wunderbaum.esm.min.js:22
          y @ wunderbaum.esm.min.js:22
          (anonymous) @ wunderbaum.esm.min.js:73
          (anonymous) @ wunderbaum.esm.min.js:6

problem is target here is null:

<img width="415" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/584e55a0-ce73-4f12-a240-35191e452714">

you rethrow the event:

<img width="255" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/f6bf1a08-083e-41fe-986f-0beded7d4ecf">


i think this describes the error:
https://stackoverflow.com/questions/67790001/event-listener-target-is-null-after-delay-with-set-time-out

**Comment by mar10** [comment]
Could you check if #65 would solve it for you?

**Comment by jogibear9988** [comment]
You need to change to:

   e => this._onChange(e)

or this is the eventhandler is null

**Comment by jogibear9988** [comment]
Culd you create a new npm when this is merged?

**Comment by mar10** [comment]
> Culd you create a new npm when this is merged?

done
