### ISSUE TITLE
Expander Arrows are sometimes not shown

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#68]
I use wunderbaum on this application: http://129.159.205.3:8082/webui/index.html

but sometimes it does not show the expand/collapse arrows, but I don't know why:

<img width="268" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/94695418-fa37-4b76-8eab-6657fc151319">

maybe you have any idea?

I use this icon-map: https://github.com/node-projects/web-component-designer/blob/eabf7b82870f876fa39e8edb926a61f07ff48db3/packages/web-component-designer-widgets-wunderbaum/src/widgets/WunderbaumOptions.ts#L23

**Comment by mar10** [comment]
It seems that the nodes with missing expanders habe wb-lazy and wb-loading classes set.
Maybe something went wrong with the dynamic loading of children?
The iconMap should also include an `expanderLazy` entry

**Comment by jogibear9988** [comment]
Problem is for example:
The "Addtional Files" node is lazy loaded. It has a collapsed icon. After expanding it gets loaded and shows the content. But it did not show an openend expander, non of the lazyloaded nodes does. And after collapsing the lazy loaded ones, they also don't show a collapsed icon any more. Also adding "expanderLazy" does not help.

These are all added:

        expanderCollapsed: new URL("../../assets/images/expander.svg", import.meta.url).toString(),
        expanderExpanded: new URL("../../assets/images/expanderClose.svg", import.meta.url).toString(),
        expanderLazy: new URL("../../assets/images/expander.svg", import.meta.url).toString(),
        folder: new URL("../../assets/images/folder.svg", import.meta.url).toString(),
        folderLazy: new URL("../../assets/images/folder.svg", import.meta.url).toString(),
        folderOpen: new URL("../../assets/images/folder.svg", import.meta.url).toString(),
        doc: new URL("../../assets/images/file.svg", import.meta.url).toString(),

my lazy loaded node data looks like this:

       {
            contextMenu: (event => screenNodeCtxMenu(event)),
            title: 'Screens',
            folder: true,
            key: 'screens',
            lazy: true,
            lazyload: (event, node) => this._lazyLoadScreensNodes(event, node)
        }

where contextMenu and lazyload are used from me for example in the wunderbaum lazyload callback:

       lazyLoad: (e) => e.node.data.lazyload(e, e.node.data),

**Comment by mar10** [comment]
There has been a corner case, where a 'loading' status was not reset (fixed now).
This was not visible, since you haven't defined the 'loading' icon, e.g.
```js
  bootstrap: {
    error: "bi bi-exclamation-triangle",
    loading: "bi bi-chevron-right wb-busy",
    ...
```

**Comment by jogibear9988** [comment]
thanks. :-)
I've never found a list of all icons I need to define. :-)

could you create a release?

**Comment by mar10** [comment]
done
