### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by Mashiane** [mar10/wunderbaum#7]
Hi

This is awesome congrats.

In a simple tree example:

q1. can one search by for example, a unique id of an item?
q2. is it possible to search for a node by a path?
q3. is it possible to perform crud functions on nodes, like adding one to its parent, updating, deleting it.

via javascript code at runtime?

Thank you.

**Comment by mar10** [comment]
Searching can be done with arbitrary patterns, even using a callback [findAll()](https://mar10.github.io/wunderbaum/api/classes/wunderbaum.Wunderbaum.html#findAll). `findKey()` searches by `node.key`.
Node traversal can be done using `visit()` or simply looping over `node..children` recursively.
Rename, remove, move create are also available using [the node API](https://mar10.github.io/wunderbaum/api/classes/wb_node.WunderbaumNode.html) and [tree API](https://mar10.github.io/wunderbaum/api/classes/wunderbaum.Wunderbaum.html)
