### ISSUE TITLE
resetLazy does not remove sub childrens "key"s, so error occurs when adding

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#70]
I add nodes to a wunderbaum node via lazyload.
Then I call resetLazy, cause the content changes.
If I now add the same objects as before, with the same keys, wunderbaum errors:

<img width="407" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/d92b55b2-0c39-45a4-83ee-70b08d80a9a1">

**Comment by mar10** [comment]
Good catch, than you!

**Comment by jogibear9988** [comment]
Could you create a release?

**Comment by jogibear9988** [comment]
Thx
