### ISSUE TITLE
Type of DragEnter is Wrong

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#73]
DragEnter at the moment could only return true/false (according to the type), but it also could return 'over', 'after' and 'before'.
So the type should be fixed

**Comment by mar10** [comment]
by the way, dragEvent was already defined in `types.ts` as 
```ts
(e: WbNodeEventType & { event: DragEvent }) => DropRegionTypeSet | boolean
```
I changed to 
```ts
(e: WbNodeEventType & { event: DragEvent }) => DropRegionType | DropRegionTypeSet | boolean
```
But it was never only boolean return value.
Where did you observe that?
