### ISSUE TITLE
DragEnter is not raised for lazy loaded not expanded nodes

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#74]
If I drag something over lazyloaded nodes wich are not yet expanded, most of the time the "dragEnter" event is not raised

**Comment by jogibear9988** [comment]
This is for me the major bug, for the others I found a workaround :-)

If you're interested, this is the UI I created with: http://129.159.205.3:8082/webui/index.html

**Comment by mar10** [comment]
... **unless** the drop operation is prevented by a rule like here
![image](https://github.com/mar10/wunderbaum/assets/41663/9a06a9e8-c2c1-4508-aee0-2d2930e3aac1)

Can you try with the `dnd.preventLazyParents: false` option?

**Comment by jogibear9988** [comment]
> dnd.preventLazyParents: false

this fixes it

**Comment by jogibear9988** [comment]
what I don't understand, if I don't drop the element on a valid target, means I let go off the mouse button, over a node wich does not allow drop, the source element keeps be grayed out... Should I create an issue for this?

**Comment by mar10** [comment]
Yes please 
Just copy your last comment into a new issue, thanks
