### ISSUE TITLE
Create Minimal Sample in JSBin, JSFiddle, Codesandbox or. smth else

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#78]
Is it possible/whised to create an official sample in one of these Online Editors? 
Should I create one?

I think this could help much to create a minimal reproducible sample for the issues. This then could be linked in the issue Template (like in Monaco Editor for example)

**Comment by mar10** [comment]
Sure, that would be a good alternative to the existing [static example](https://github.com/mar10/wunderbaum/blob/main/test/triage/issue_000.html)

**Comment by jogibear9988** [comment]
https://jsbin.com/lecasinava/edit?html,js,output
