### ISSUE TITLE
setSelected causes rerender

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#81]
**Describe the bug**
if you setSelected of an node, every node is rerendered. Is this expected?

**To Reproduce**
Look at the sample

**Expected behavior**
Only the selected (or none) should be rerendered

**Minimal Reproducible Example**
https://jsbin.com/qamihoboko/edit?html,js,console,output

**Comment by jogibear9988** [comment]
still relevant...

**Comment by mar10** [comment]
There are several situations, where selecting a node will update sibling, descendants and/or ancestor nodes as well.
Therefore the update code is wrapped in [`runWithDeferredUpdate`](https://mar10.github.io/wunderbaum/api/classes/wunderbaum.Wunderbaum.html#runWithDeferredUpdate).
This may be optimized for special cases, but given the fast execution time I think it is not worth the extra complexity atm.
