### ISSUE TITLE
Drag/Drop of nodes does not work any more, in 0.8.0 it works

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#82]
Thank you for your contribution.

See [here](https://mar10.github.io/wunderbaum/index.html#/tutorial/contribute) for the contribution guidelines.

**Describe the bug**
You could not use D&D to move nodes, see the sample: https://jsbin.com/xomonebupe/edit?html,js,console,output
(If you change wunderbaum to version 0.8.0 in the sample, it works)

**Expected behavior**
D&D of nodes should be workin

**Minimal Reproducible Example**
https://jsbin.com/xomonebupe/edit?html,js,console,output

**Desktop (please complete the following information):**

- OS: MacOS
- Chrome
- Latest

**Comment by jogibear9988** [comment]
thinke the error is here:

https://github.com/mar10/wunderbaum/commit/ee131fc83198be0637c0a8e019fa85f6f2201044#diff-4d536724aed7f97d1d802ee4e41d8e55e439afed82939f167c16897b9dd7eaf9R419

**Comment by jogibear9988** [comment]
maybe change the predicate of _t to a bool, to prevent such errors?

**Comment by mar10** [comment]
Thank you!
