### ISSUE TITLE
rowHeightPx is ignored

### ISSUE THREAD

**Issue by creffect** [mar10/wunderbaum#83]
**Describe the bug**
The option "rowHeightPx" is ignored. It seems, that ROW_HEIGHT in the source code is always a constant and not changeable from 22px. (export const ROW_HEIGHT = 22 in common.ts)

**To Reproduce**
`const tree = new Wunderbaum({
      element: this.treeElement.nativeElement,
      source: [{title: "Test"}],
      rowHeightPx: 40
});
`
**Expected behavior**
Row height is adjustable (for usability reasons).

Thank you for checking!

**Comment by elevenlabsdev** [comment]
Hello, to add to this: Would it also be possible to make the row height dynamic, e.g. depending on the row content?

Many thanks!

**Comment by mar10** [comment]
> Hello, to add to this: Would it also be possible to make the row height dynamic, e.g. depending on the row content?
> 
> Many thanks!

This would be way more complicated, since then we cannot define simple CSS rules for rows or calculate viewport sizes by simple multiplication. This should be discussed in a separate thread.
