### ISSUE TITLE
After editing a node title a javascript error "Cannot read properties of null (reading '_render')" occurs

### ISSUE THREAD

**Issue by creffect** [mar10/wunderbaum#84]
**Describe the bug**
After editing a node title a javascript error "Cannot read properties of null (reading '_render')" occurs

**To Reproduce**
1. Open official demo: https://mar10.github.io/wunderbaum/demo/#demo-plain
2. Edit any nodes title
3. check console for errors

**Expected behavior**
Editing titles should be possible without javascript errors.

**Comment by mar10** [comment]
I couldn't reproduce, pleas give more details
 (note that some examples simulate a validation error if as number is inserted into the title)

**Comment by creffect** [comment]
I use the latest version of chrome. I edited the title of the selected node.


<img width="1379" alt="Bildschirmfoto 2024-02-27 um 17 36 16" src="https://github.com/mar10/wunderbaum/assets/8288442/e4a55dc1-9cba-4f57-84e4-7b1b5ff8e0eb">

**Comment by mar10** [comment]
Didn't appear on Safari, but I could reproduce it with Chromium
