### ISSUE TITLE
Enhance filtering to show leafs of any matched parent node with filter mode='hide'

### ISSUE THREAD

**Issue by devilsnare007** [mar10/wunderbaum#89]
For the purpose of these issues/requests please refer to the Large Grid demo:
https://mar10.github.io/wunderbaum/demo/#demo-large

**Is your feature request related to a problem? Please describe.**
1. I read through the documentation but cannot figure out if there is an option to render the leafs of any matched node when filtering with hide option enabled 
2. Not sure if there is a way to filter while searching multiple columns simultaneously (so in addition to the searching on the Product column with the existing text search box, have a text search box for each column header such that it filters them all simultaneously).

**Describe the solution you'd like**
For example in the demo-large example, if you filter with keyword 'Pungent', and have the filter set to 'Hide unmatched nodes', it hides the children as well of the 'Pungent Potatos' node. 
I was expecting the children leafs/nodes of 'Pungent Potatos' to be rendered as well.

**Comment by fnajera-rac-de** [comment]
I received a request for exactly this behavior a couple of days ago. It's very confusing to see the "expand arrow" that can be toggled but not see any children at all.

**Comment by mar10** [comment]
Have you tried calling [tree. filterBranches()](https://mar10.github.io/wunderbaum/api/classes/wunderbaum.Wunderbaum.html#filterBranches) instead of [tree. filterNodes()](https://mar10.github.io/wunderbaum/api/classes/wunderbaum.Wunderbaum.html#filterNodes)?

**Comment by devilsnare007** [comment]
@mar10 - tree.filterBranches() works perfectly, although there is no option to do so in [FilterOptionsType](https://mar10.github.io/wunderbaum/api/types/types.FilterOptionsType.html)

Can you also please provide some guidance if there is a way to search/filter on all columns (Author, Qty, Sale, etc.)?
